<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZenAQc\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZenAQc/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXZenAQc.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXZenAQc\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXZenAQc\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XZenAQc',
    'container.build_id' => '87e10309',
    'container.build_time' => 1537202062,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZenAQc');
