<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCWLf1WN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCWLf1WN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCWLf1WN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCWLf1WN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCWLf1WN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CWLf1WN',
    'container.build_id' => '6efc8090',
    'container.build_time' => 1537133801,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCWLf1WN');
